# Generated by Django 4.2.25 on 2025-10-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='summary',
            field=models.TextField(blank=True, help_text='Quick summary or key points for the front of the flashcard. Markdown is supported.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(help_text='Detailed explanation for the back of the flashcard. Markdown is supported.'),
        ),
    ]
